# -*- coding: utf-8 -*-
"""Stack&Queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tT0yUvHfNb-UUR_hv77M7FA0C-3aiHVi

🟦 STACKS IN PYTHON (LIFO)
"""

print("🟦 STACK (Last In First Out)")
# ✅ Creating an empty stack
stack = []

# ✅ Pushing elements
stack.append('A')
stack.append('B')
stack.append('C')

print("Current Stack:", stack)

# ✅ Popping the top element (removes last pushed)
top_element = stack.pop()
print("Popped Element:", top_element)
print("Stack after pop:", stack)

# ✅ Peeking at the top (without removing)
if stack:
    print("Top Element (peek):", stack[-1])
else:
    print("Stack is empty")

# ✅ Checking if stack is empty
if not stack:
    print("Stack is empty")
else:
    print("Stack is NOT empty")

"""🟩 QUEUES IN PYTHON (FIFO)

"""

# ✅ Importing deque from collections
from collections import deque

# ✅ Creating an empty queue
queue = deque()

# ✅ Enqueuing elements
queue.append('Task1')
queue.append('Task2')
queue.append('Task3')

print("Current Queue:", list(queue))

# ✅ Dequeuing the front element (removes first inserted)
front_task = queue.popleft()
print("Dequeued Element:", front_task)
print("Queue after dequeue:", list(queue))

# ✅ Peeking at the front (without removing)
if queue:
    print("Front Element (peek):", queue[0])
else:
    print("Queue is empty")

# ✅ Checking if queue is empty
if not queue:
    print("Queue is empty")
else:
    print("Queue is NOT empty")